baseURL: 'http://localhost:1313/'
languageCode: 'en-us'
title: 'Javed Hussain'
theme: 'zenex'

menu:
  main:
  - identifier: home
    name: Home
    pre: house
    url: #
    weight: -110
    params:
      active: true

  - identifier: blog
    name: Blog
    pre: feather
    url: #
    weight: -100

  social:
  - identifier: linkedin
    name: linkedin
    pre: fa-brands fa-linkedin
    url: #
    weight: 1

  - identifier: instagram
    name: instagram
    pre: fa-brands fa-instagram
    url: #
    weight: 2

  - identifier: twitter
    name: Twitter
    pre: fa-brands fa-square-twitter
    url: #
    weight: 3

  - identifier: resume
    name: Resume
    pre: fa-solid fa-file-pdf
    url: #
    weight: 4

params:
  name: Javed Hussain
  summary: |-
    Senior Software engineer with more than 5 years of experience
    in building scalable and robust software solutions using,
    but not limited to <code>Java</code>
  avatar: images/me_javed.jpg
